In [ ]:

import pandas as pd
data={'Date':['2023-03-18','2023-03-19','2023-03-18','2023-03-19'],'city':['BKNR','KMR','BKNR','KMR'],
      'N01_rice':[20,30,40,60],'No2_rice':[60,70,80,90]}
df=pd.DataFrame(data) 
df

         Date  city  N01_rice  No2_rice
0  2023-03-18  BKNR        20        60
1  2023-03-19   KMR        30        70
2  2023-03-18  BKNR        40        80
3  2023-03-19   KMR        60        90

In [40]:
df = df.drop_duplicates(['Date','city'])

df.pivot(index='Date', columns='city', values='N01_rice')

city        BKNR   KMR
Date
2023-03-18  20.0   NaN
2023-03-19   NaN  30.0